################################################################################
### tables.R
### Copyright (c) Joshua Hamilton, 2024
### Email: joshamilton@gmail.com
### Functions for working with tag dataframe
################################################################################

#' Filter a dataframe of field (tag) values
#'
#' This function filters a dataframe to retain only the columns specified in
#' the columns_to_retain argument. It then removes duplicate rows.
#'
#' @param dataframe a dataframe generated from an XML file by the function
#' xml_to_dataframe
#' @param columns_to_retain a character vector of column names to retain
#'
#' @return a dataframe containing only the columns specified in the
#' columns_to_retain argument. Filtered for unique rows.
#' @export
#'
#' @examples
#' columns_to_retain = c('Genre', 'Composer', 'Work', 'Orchestra', 'Year Recorded', 'Album', 'Conductor', 'Soloists')
#' tag_df = xml_to_dataframe(system.file('extdata', 'library.xml', package = 'jRiverExplorer'))
#' tag_df = filter_dataframe(tag_df, columns_to_retain)
filter_dataframe = function(dataframe,
                            columns_to_retain = c('Genre', 'Composer', 'Work', 'Orchestra', 'Year Recorded', 'Album', 'Conductor', 'Soloists')) {
  dataframe %>%
    dplyr::select(dplyr::all_of(columns_to_retain)) %>%
    dplyr::distinct()
}

#' Expand dataframe to include 'Orchestra or Soloist' field
#'
#' This function creates a new field 'Orchestra or Soloist' which is 1 if either
#' the 'Orchestra' or 'Soloists' fields have a value, and NA otherwise.
#'
#' Intended to be used with completeness functions
#'
#' @param tag_df a dataframe generated by the 'filter_dataframe' function
#'
#' @return a dataframe with a new field 'Orchestra or Soloist'
#' @importFrom rlang .data
#' @export
#'
#' @examples
#' columns_to_retain = c('Genre', 'Composer', 'Work', 'Orchestra', 'Year Recorded', 'Album', 'Conductor', 'Soloists')
#' tag_df = xml_to_dataframe(system.file('extdata', 'library.xml', package = 'jRiverExplorer'))
#' tag_df = filter_dataframe(tag_df, columns_to_retain)
#' tag_df = expand_df(tag_df)
expand_df = function(tag_df) {
  tag_df %>% dplyr::mutate(`Orchestra or Soloist` = ifelse(!is.na(.data$Orchestra) | !is.na(.data$Soloists), 1, NA))
}

#' Convert the tag_df to long format
#'
#' This function takes a dataframe from 'filter_dataframe' or make_tag_completeness_df
#' and converts it to long format. It then filters out any rows with NA values.
#'
#' @param tag_df a dataframe generated by the 'filter_dataframe' function
#'
#' @return a dataframe in long format, with NA values removed
#' @importFrom rlang .data
#' @export
#' @examples
#' columns_to_retain = c('Genre', 'Composer', 'Work', 'Orchestra', 'Year Recorded', 'Album', 'Conductor', 'Soloists')
#' tag_df = xml_to_dataframe(system.file('extdata', 'library.xml', package = 'jRiverExplorer'))
#' tag_df = filter_dataframe(tag_df, columns_to_retain)
#' tag_df = make_long_tag_df(tag_df)
make_long_tag_df = function(tag_df) {
  tag_df %>%
    tidyr::pivot_longer(cols = dplyr::everything(), names_to = 'Field', values_to = 'Value') %>%
    dplyr::filter(!is.na(.data$Value)) %>%
    dplyr::distinct() %>%
    dplyr::mutate(Field = as.factor(.data$Field))
}

# Convert dataframe of unique tag values to dataframe of tag completeness
# For each tag, calculate the proportion of items which have a value. The user
# can use the results to determine which tags are incomplete.
make_tag_completeness_df = function(tag_df){
  expand_df(tag_df) %>%
    dplyr::summarize(dplyr::across(dplyr::everything(), ~ sum(!is.na(.)) / dplyr::n(), .names = '{.col}'))
}

# Get unique values from the completeness dataframe
field_values_from_completeness_df = function(tag_df) {
  levels(make_long_tag_df(
    make_tag_completeness_df(tag_df))
    $Field)
}

# Get unique values from the uniqueness dataframe
field_values_from_uniqueness_df = function(tag_df) {
  levels(make_long_tag_df((tag_df))$Field)
}

# Retrieve items missing a tag value
select_untagged_values = function(tag_df, field) {
  tag_df %>% dplyr::filter(is.na(.data[[field]]))
}

# Retrieve unique values for a tag
select_unique_tag_values = function(tag_df, field) {
  make_long_tag_df(tag_df) %>%
    dplyr::filter(.data$Field == field) %>%
    dplyr::filter(!is.na(.data$Value)) %>%
    dplyr::arrange(.data$Value) %>%
    dplyr::select(.data$Value)
}
